### ISSUE TITLE
Rename package to more general name?

### ISSUE THREAD

**Issue by LinguList** [calc-project/soundvectors#14]
I was thinking about renaming the package, now, that we are in principle away from "clts", as we have as input a string that represents a sound by its features. This system -- provided features from CLTS are used (but CLTS is also pretty standard, in fact, clts mimicks the IPA) -- is more general than CLTS itself. The 2vec is also a phrase that is usually for embeddings, but the vectors are derived from features, and the feature is the core.

**Comment by LinguList** [comment]
Names occurring to me are: `soundvecs` with class `SoundVecs` or `featvecs` with class `FeatVecs` for "feature vectors", since we have vectors corresponding to features. Or just `soundvectors` ? (of course [distfeat](https://pypi.org/project/distfeat/) already exists, but this is of course obvious, and the name is anyway rather ugly). 

BTW: if we don't mention, we should probably add [ipasymbols](https://pypi.org/project/ipasymbols/) to the list of packages available in the paper and also emphasize why we go beyond.

**Comment by arubehn** [comment]
I agree, in fact I had also thought about that already. Out of these options, I prefer `featvecs`, but I am honestly not thrilled by either of these names. Maybe let's take some more time to brainstorm :)

Thank you for pointing out the `ipasymbols` package, I wasn't aware of it. I will make sure to include it in the paper!

**Comment by LinguList** [comment]
Let us brainstorm a little.

**Comment by LinguList** [comment]
You can do it now. You are admin :-)

**Comment by arubehn** [comment]
Cool, thanks - already done :)
